# Builder
FROM containers.chewed-k8s.net/docker_hub_cache/library/node:20-alpine AS builder

WORKDIR /frontend

COPY package*.json ./
COPY yarn.lock ./
RUN yarn install

COPY . .
RUN yarn build

# Runner
FROM containers.chewed-k8s.net/docker_hub_cache/library/nginx:1.23-alpine AS runner
COPY --from=builder /frontend/build /usr/share/nginx/html
COPY ./k8s/nginx.conf /etc/nginx/conf.d/default.conf

RUN apk update
RUN apk upgrade

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
