# Builder
FROM containers.chewed-k8s.net/docker_hub_cache/library/node:20-alpine AS builder

WORKDIR /frontend

# Install dependencies
COPY vendor ./vendor
COPY package*.json ./
COPY yarn.lock ./
RUN yarn config set registry https://
RUN yarn install

# Build
COPY public ./public
COPY src ./src
COPY public ./public
COPY tsconfig.json ./
COPY .env.production ./.env
RUN yarn build

# Runner
FROM containers.chewed-k8s.net/docker_hub_cache/library/nginx:1.25-alpine AS runner
COPY --from=builder /frontend/build /usr/share/nginx/html
COPY ./k8s/nginx.conf /etc/nginx/conf.d/default.conf

RUN apk update
RUN apk upgrade

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
