name: Deploy

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: containers.chewed-k8s.net/todo-list/frontend
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{raw}}
            type=sha
      - name: QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
      - name: Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Cache
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ github.sha }}
      - name: Login Github
        uses: docker/login-action@v2
        with:
          registry: containers.chewed-k8s.net
          username: robot$todo-list+github
          password: ${{ secrets.CONTAINERS_KEY }}
      - name: Create .env.production
        run: |
          echo "REACT_APP_KEYCLOAK_URL=${{ vars.KEYCLOAK_URL }}" > .env.production
          echo "REACT_APP_KEYCLOAK_CLIENT_ID=${{ secrets.KEYCLOAK_CLIENT_ID }}" >> .env.production
          echo "REACT_APP_KEYCLOAK_CLIENT_SECRET=${{ secrets.KEYCLOAK_CLIENT_SECRET }}" >> .env.production
          echo "REACT_APP_BACKEND_URL=${{ vars.BACKEND_URL }}" >> .env.production
          echo "REACT_APP_PRODUCTION=${{ vars.PRODUCTION }}" >> .env.production
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          builder: ${{ steps.buildx.outputs.name }}
          file: ./k8s/Containerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          build-args:
            VERSION=${{ steps.meta.outputs.tags }}
            BUILD=${{ github.sha }}
            SERVICE_NAME=frontend
#  deploy:
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#      - name: Deploy
#        uses: k8sdeploy/github-action@v1
#        with:
#          service-namespace: k8sdeploy
#          service-name: hooks-service
#          k8sdeploy-key: ${{ secrets.K8SDEPLOY_KEY }}
#          k8sdeploy-secret: ${{ secrets.K8SDEPLOY_SECRET }}
#          k8sdeploy-id: ${{ secrets.K8SDEPLOY_ID }}
#          image-hash: ${{ github.sha }}
#          image-tag: ${{ github.ref_name }}

